<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)\jars\**\*.*">
			<Link>jars\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Visible>false</Visible>
		</None>
		<None Include="$(MSBuildThisFileDirectory)\config\**\*.*">
			<Link>config\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Visible>false</Visible>
		</None>
	</ItemGroup>
</Project>