#
# Module manifest for module 'MASES.KNetPS'
#
# Generated by: MASES s.r.l.
#

@{

RootModule = 'MASES.KNetPS.psm1'

ModuleVersion = '1.4.4'

# CompatiblePSEditions = @()

GUID = '799c6600-abd6-4f6d-92f1-301a056f3f1b'

Author = 'MASES s.r.l.'

CompanyName = 'MASES s.r.l.'

Copyright = 'Copyright ©  MASES s.r.l. 2022'
Description = 'KNet PowerShell (aka KNetPS) is a PowerShell Module to use Apache Kafka and PowerShell side-by-side. With KNetPS it is possible to:
- execute all commands of Apache Kafka within a PowerShell shell: Administration, Consumer, Producer, Stream, Connect, server side (Kafka and ZooKeeper)
- create Apache Kafka objects: consumers, producers, etc

More information within the project hosted on GitHub at https://github.com/masesgroup/KNet for further information.'

# PowerShellVersion = ''

# PowerShellHostName = ''

# PowerShellHostVersion = ''

# DotNetFrameworkVersion = ''

# CLRVersion = ''

# ProcessorArchitecture = ''

# RequiredModules = @()

# RequiredAssemblies = @()

# ScriptsToProcess = @()

# TypesToProcess = @()

# FormatsToProcess = @()

# NestedModules = @()

FunctionsToExport = @()

CmdletsToExport = @(
    'Start-KNetPS',
    'New-KObject',
    'Start-AclCommand',
    'Start-BrokerApiVersionsCommand',
    'Start-ConfigCommand',
    'Start-ConsumerGroupCommand',
    'Start-DelegationTokenCommand',
    'Start-DeleteRecordsCommand',
    'Start-FeatureCommand',
    'Start-LeaderElectionCommand',
    'Start-LogDirsCommand',
    'Start-MetadataQuorumCommand',
    'Start-ReassignPartitionsCommand',
    'Start-TopicCommand',
    'Start-ZkSecurityMigrator',
    'Start-KafkaStart',
    'Start-ZooKeeperShell',
    'Start-ZooKeeperStart',
    'Start-MetadataShell',
    'Start-ClusterTool',
    'Start-ConsoleConsumer',
    'Start-ConsoleProducer',
    'Start-ConsumerPerformance',
    'Start-DumpLogSegments',
    'Start-GetOffsetShell',
    'Start-MirrorMaker',
    'Start-ProducerPerformance',
    'Start-ReplicaVerificationTool',
    'Start-StorageTool',
    'Start-StreamsResetter',
    'Start-TransactionsCommand',
    'Start-VerifiableConsumer',
    'Start-VerifiableProducer',
    'Start-ConnectDistributed',
    'Start-ConnectStandalone',
    'Start-MirrorMaker2'
)

VariablesToExport = '*'

AliasesToExport = @()

# DscResourcesToExport = @()

# ModuleList = @()

# FileList = @()

PrivateData = @{

    PSData = @{

        Tags = @('KNetPS', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows', 'Linux', 'ZooKeeper', 'Kafka', 'Apache Kafka', 'Admin', 'Consumer', 'Producer')

        LicenseUri = 'https://github.com/masesgroup/JNet/blob/master/LICENSE'

        ProjectUri = 'https://github.com/masesgroup/JNet'

        IconUri = 'https://github.com/masesgroup/JNet/blob/master/src/net/Common/JCOB128x128.png'

        ReleaseNotes = 'https://github.com/masesgroup/JNet/releases'

    }

} 

HelpInfoURI = 'https://masesgroup.github.io/JNet/articles/usagePS.html'

# DefaultCommandPrefix = ''
}

